name: Build pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Maven Clean
        run: |
          mvn clean
      - name: Maven Tests
        run: |
          mvn test
      - name: Maven Build
        run: |
          mvn package spring-boot:repackage -DskipTests
      - name: Versioning
        run: |
          touch version.txt
          date +%s >> version.txt
          mv ./version.txt ./target
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
              target/*.jar
              target/version.txt

